version: '3'
services:
  vault:
    image: "vault:1.4.0"
    volumes:
      - "./vault/data:/vault/data"
      - "./vault/config:/vault/config"
    environment:
      - "SKIP_SETCAP=true"
    command: server
    ports:
      - "8200:8200"
  postgres:
    image: "postgres:12.2-alpine"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
      - "./postgres/config/postgres_server.pem:/var/lib/postgresql/server.crt"
      - "./postgres/config/postgres_server-key.pem:/var/lib/postgresql/server.key"
    environment:
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=admin"
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - "5432:5432"
